
# nothing here
#CONFIG_SHELL=y
CONFIG_ESP32_USE_UNSUPPORTED_REVISION=y
#CONFIG_LV_Z_FLUSH_THREAD=y
#CONFIG_CPP=y
#CONFIG_STD_CPP17=y
#CONFIG_LOG=y
#CONFIG_SPI_LOG_LEVEL_DBG=y


CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_NO_OPTIMIZATIONS=n

# Display subsystem
CONFIG_DISPLAY=y
CONFIG_LVGL=y
CONFIG_LV_Z_MEM_POOL_SIZE=32768
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_IDLE_STACK_SIZE=2048

CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_COLOR_16_SWAP=y

CONFIG_LV_FONT_DEFAULT_MONTSERRAT_14=n
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_22=y

CONFIG_SPI=y
CONFIG_MIPI_DBI=y
CONFIG_MIPI_DBI_SPI=y

#CONFIG_LV_USE_CACHE=n
#CONFIG_LV_USE_IMAGE_CACHE=n
#CONFIG_LV_USE_IMAGE_DECODER=n

# LVGL
#CONFIG_LVGL_USE_LABEL=y
#CONFIG_LVGL_USE_FONT_DEFAULT_SMALL=y
#CONFIG_LVGL_BITS_PER_PIXEL=16
