
# nothing here
#CONFIG_SHELL=y
CONFIG_ESP32_USE_UNSUPPORTED_REVISION=y
#CONFIG_LV_Z_FLUSH_THREAD=y
#CONFIG_CPP=y
#CONFIG_STD_CPP17=y
#CONFIG_LOG=y
#CONFIG_SPI_LOG_LEVEL_DBG=y

# Display subsystem
CONFIG_DISPLAY=y
CONFIG_SPI=y
#CONFIG_SPI_ESP32=y
CONFIG_MIPI_DBI=y
CONFIG_MIPI_DBI_SPI=y
CONFIG_LV_Z_MEM_POOL_SIZE=32768
CONFIG_LV_USE_MATRIX=y

#CONFIG_LV_USE_CACHE=n
#CONFIG_LV_USE_IMAGE_CACHE=n
#CONFIG_LV_USE_IMAGE_DECODER=n

# LVGL
CONFIG_LVGL=y
#CONFIG_LVGL_USE_LABEL=y
#CONFIG_LVGL_USE_FONT_DEFAULT_SMALL=y

# LVGL display buffer settings
#CONFIG_LVGL_BITS_PER_PIXEL=16
